runtime: nodejs14 # or another supported version
service: webrtc-rest

manual_scaling:
  instances: 1

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

network: # adding for socket.io
  session_affinity: true

# this file is being used for uploading the app to compute engine